# Generated by Django 4.2.4 on 2023-08-18 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_created_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='collaborators',
        ),
        migrations.RemoveField(
            model_name='user',
            name='auth_user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='created_event',
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
    ]
